version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: estadao-test-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'estadao_test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      args:
        user: estadao
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: estadao-test-dev
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    container_name: estadao-test-dev-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      APPLICATION_ENV: development
      XDEBUG_INSTALL: 1
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      XDEBUG_REMOTE_ENABLE: "on"
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_REMOTE_HANDLER: dbgp
      XDEBUG_PROFILER_ENABLE: 1
      XDEBUG_PROFILER_OUTPUT_DIR: /var/www/html/xdebug.log
      XDEBUG_REMOTE_PORT: 9003
      XDEBUGINI_PATH: /usr/local/etc/php/conf.d/xdebug.ini
      XDEBUG_DEFAULT_ENABLE: 1
      XDEBUG_IDEKEY: PHPSTORM
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: estadao-test-dev-nginx
    restart: unless-stopped
    expose:
      - 9003
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local
