version: "3"

services:
  app:
    image: wyveo/nginx-php-fpm:php74
    ports: 
      - "8095:80"
    volumes: 
      - ./:/usr/share/nginx
    networks: 
      - app-network

  mysql-app: 
    image: mysql:5.7.33
    ports: 
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: test-dev
      MYSQL_ROOT_PASSWORD: laravel
    networks: 
      - app-network 

  nginx:
    image: nginx:alpine
    container_name: estadao-test-dev-nginx
    restart: unless-stopped
    expose:
      - 9003
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app

networks: 
  app-network: 
    driver: bridge