version: '3.7'

services:
  lumen:    
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-lumen
    links:
      - db
    ports:
      - '8000:8000'
    expose:
      - '8000'
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: ddsds2345t67y7udnpsdf9wjn903r034ht04hygt04h
      DB_CONNECTION: mysql
      DB_HOST: estadao_db
      DB_DATABASE: estadao_test
      DB_USERNAME: root
      DB_PASSWORD: password
    networks:
      - estadao
    depends_on:
      - db

  db:
    image: mysql
    container_name: estadao_db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: estadao_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./backend/resources/mysql/db_init.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - estadao

  nuxt:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend-nuxt
    restart: always
    ports:
      - '80:80'
    networks:
      - estadao

volumes:
  mysql_data: { driver: local }

networks:
  estadao:
    driver: bridge
