version: "3.7"
services:
  app:
    build:
      args:
        user: estadao
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: estadao-test-dev
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    container_name: estadao-test-dev-app
    restart: unless-stopped
    working_dir: /var/www/lumen
    volumes:
      - ./lumen:/var/www/lumen
    environment:
      APPLICATION_ENV: development
      XDEBUG_INSTALL: 1
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      XDEBUG_REMOTE_ENABLE: "on"
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_REMOTE_HANDLER: dbgp
      XDEBUG_PROFILER_ENABLE: 1
      XDEBUG_PROFILER_OUTPUT_DIR: /var/www/html/xdebug.log
      XDEBUG_REMOTE_PORT: 9003
      XDEBUGINI_PATH: /usr/local/etc/php/conf.d/xdebug.ini
      XDEBUG_DEFAULT_ENABLE: 1
      XDEBUG_IDEKEY: PHPSTORM
    networks:
      - nginx-proxy

  node:
    image: node
    tty: true
    container_name: estadao-test-dev-node
    restart: unless-stopped
    working_dir: /var/www/vuejs
    volumes:
      - ./vuejs:/var/www/vuejs
    networks:
      - nginx-proxy
    ports:
      - "8080:81"

  nginx:
    image: nginx:alpine
    container_name: estadao-test-dev-nginx
    tty: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=estadao.local
    expose:
      - 9003

networks:
  nginx-proxy:
    driver: bridge