version: "3.7"
services:
  app:
    build:
      args:
        user: estadao
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: estadao-test-dev
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    container_name: estadao-test-dev-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      APPLICATION_ENV: development
  nginx:
    image: nginx:alpine
    container_name: estadao-test-dev-nginx
    restart: unless-stopped
    expose:
      - 9003
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
  mysql:
    image: mysql:5.7
    container_name: mysql-teste
    #restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=100200
      - MYSQL_USER=alpha
      - MYSQL_PASSWORD=100200
    ports:
      - 3306:3306      