version: "3.7"
services:
  app:
    build:
      args:
        user: estadao
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: estadao-test-dev
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    container_name: estadao-test-dev-app
    restart: unless-stopped
    working_dir: /var/www    
    volumes:
      - ./src:/var/www
    environment:
      APPLICATION_ENV: development
      XDEBUG_INSTALL: 1
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      XDEBUG_REMOTE_ENABLE: "on"
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_REMOTE_HANDLER: dbgp
      XDEBUG_PROFILER_ENABLE: 1
      XDEBUG_PROFILER_OUTPUT_DIR: /var/www/html/xdebug.log
      XDEBUG_REMOTE_PORT: 9004
      XDEBUGINI_PATH: /usr/local/etc/php/conf.d/xdebug.ini
      XDEBUG_DEFAULT_ENABLE: 1
      XDEBUG_IDEKEY: PHPSTORM
    networks:
      - rede  

 

  nginx:
    image: nginx:alpine
    container_name: estadao-test-dev-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
      - mysql 
    networks:
      - rede  
  

  mysql:
    image: mysql:5.7.32
    container_name: mysql-estadao
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: teste
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: estadao
    networks:
      - rede  
  
networks:
  rede:
    name: rede      