
<div class="container" style="padding-top: 56px;">
   <h3 id="title">Novo Carro</h3>
    <div class="col-md-6">
        <div class="resposta"></div>
        <form action="post ">
            <input type="hidden" name="id">
            <div class="form-group">
               <label >Marca</label>
               <input type="text" name="marca" class="form-control" placeholder="Marca">
            </div>
            <div class="form-group">
               <label >Modelo</label>
               <input type="text" name="modelo" class="form-control" placeholder="Modelo">
            </div>
           <div class="form-group">
              <label >Ano</label>
              <input type="number" name="ano" class="form-control" placeholder="Ano">
           </div>
    
           <button type="submit" class="btn btn-primary">Salvar</button>
        </form>

    </div>
</div>