<header class="jumbotron my-4">
    <h1 class="display-3">Bem Vindo!</h1>
    <p class="lead">Este é o site/atividade para a vaga de Desenvolvedor Web na Slice!<br>Esta Single Page Application foi desenvolvido em PHP e JavaScript puro (classe por classe, commit por commit), sem o uso de frameworks além do Bootstrap CSS.<br>Espero que atenda (ou até mesmo exceda) as expectativas!</p>
    <button class="btn btn-primary btn-lg act" act="load_insert_form" onclick="RC.LoadInsertForm()">Inserir novo carro!</button>
</header>
<div class="resposta"></div>
<div class="row text-center cars">
</div>