<div class="container" style="padding-top: 56px;">
    <div class="col-md-6">
        <form action="post ">
            <input type="hidden" name="id">
           <div class="form-group">
              <label >Modelo</label>
              <input type="text" name="modelo" class="form-control" placeholder="Modelo">
           </div>
           <div class="form-group">
              <label >Marca</label>
              <input type="text" name="marca" class="form-control" placeholder="Modelo">
           </div>
           <div class="form-group">
              <label >Ano</label>
              <input type="text" name="ano" class="form-control" placeholder="Modelo">
           </div>
    
           <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>
</div>