<footer>
    <div class="footer__sub">
        <div class="container">
            Gérlisson Paulino - <i class="fa fa-whatsapp" aria-hidden="true"></i> 15.99685.9648 (WhatsApp)
            <div class="developer">
                <a href="https://www.onfour.com.br" title="Portfólio" target="_blank">&raquo; Portfólio</a>
            </div>
        </div>
    </div>
</footer>

<script src="<?php echo URL_MAIN; ?>/public/assets/js/bootstrap.min.js"></script>
<script src="<?php echo URL_MAIN; ?>/public/assets/js/vehicle.js"></script>

</body>
</html>