<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"  content="minimal-ui,width=device-width, initial-scale=1">

    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">

    <title>Teste para desenvolvedor do Estadão | Gérlisson Paulino </title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="<?php echo URL_MAIN; ?>/public/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo URL_MAIN; ?>/public/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?php echo URL_MAIN; ?>/public/assets/css/main.min.css">
    
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body id="top">
<header>
    <nav class="navbar navbar-custom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="<?php echo URL_MAIN; ?>" title="" class="navbar-brand">
                    <h1>Teste para desenvolvedor do Estadão</h1>
                </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="<?php echo URL_MAIN; ?>/veiculos" title="Veículos">
                            Veículos
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>