<section>
    <div class="container">
        <div class="row">

            <div class="col-lg-12">
                <h2>O que foi utilizado no desenvolvimento</h2>
                <ul>
                    <li>Linux</li>
                    <li>OOP</li>
                    <li>PHP7</li>
                    <li>Biblioteca Bootstrap v3.3.7</li>
                    <li>HTML / HTML5</li>
                    <li>CSS / CSS3 / SASS</li>
                    <li>Javascript</li>
                    <li>Biblioteca JQuery</li>
                    <li>Ajax</li>
                    <li>MySQL</li>
                    <li>MySQL Workbench</li>
                    <li>Doctrine 2</li>
                    <li>Composer</li>
                    <li>PHPUnit</li>
                </ul>

                <hr />

                <h2>Configuração da aplicação</h2>
                <h3>Passo 1:</h3>
                <p>Criar uma tabela no banco dados, e importar o arquivo "database.sql" que se encontra na raiz da aplicação.</p>

                <h3>Passo 2:</h3>
                <p>Configurar o arquivo de conexão com o banco de dados "config/local.php".</p>

                <h3>Passo 3:</h3>
                <p>Fazer download das dependencias via console, comando: <small>composer install</small></p>

                <h3>Passo 4 (Opcional):</h3>
                <p>Gerar as Proxies para mapeamento das tabelas do banco de dados, via console: <small>php vendor/doctrine/orm/bin/doctrine orm:generate-proxies</small></p>
                <p>Caminho: "data/Proxies"</p>
                
            </div>
        </div>
    </div>
</section>