function CustomLoading() {
    {/* <!-- [ldio] generated by https://loading.io/ --> */ }
    return (<>
        <svg className="loading" width="200px" height="200px" viewBox="0 0 100 100">
            <path d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50" fill="#e15b64" stroke="none" >
            </path>
        </svg>
    </>
    )
}

export default CustomLoading;