<!DOCTYPE html>
<html lang="pt-br">

    <head>
        <meta charset="utf-8">
        <title><?=$this->title?></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    </head>

    <body host="<?=HOST?>">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                    <a class="navbar-brand" href="#">Estadão</a>
                    <div class="pull-right ">
                        <ul class="navbar-nav ">
                            <li class="nav-item active">
                                <a class="nav-link act" act="load_home">Home</a>
                            </li>
                            <li class="nav-item">
                                <!-- <a class="nav-link" href="#" onclick="RC.LoadHome()">Inserir novo carro</a> -->
                            </li>
                        </ul>
                    </div>

            </div>
        </nav>

        <div id="content" class="container">



        </div>
    </body>

</html>
<script src="<?=HOST?>templates/estadao/src/js/main.js"></script>
<style>
    body {
        padding-top: 56px;
    }

</style>
<script>
document.addEventListener("DOMContentLoaded", function(event) { 
    RC.LoadHome();

    acts = document.querySelectorAll(".act"); 
    
    
    for (var i = 0; i < acts.length; i++) {
        var act = acts[i];
        act.addEventListener("click", function(e){
            e.preventDefault();
            switch(this.getAttribute("act")){
                case "load_home":
                    RC.LoadHome();
                    break;
                case "load_insert_form":
                    RC.LoadInsertForm();
                    break;
                case "load_update_form":
                    RC.LoadUpdateForm(this.getAttribute("id"));
                    break;
            }
        });

    }


});

</script>