<!DOCTYPE html>
<html lang="pt-br">

    <head>
        <meta charset="utf-8">
        <title><?=$this->title?></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    </head>

    <body host="<?=HOST?>">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                    <span class="navbar-brand" style="cursor:pointer" onclick="RC.LoadHome()">Estadão</span>
                    <div class="pull-right ">
                        <ul class="navbar-nav ">
                            <li class="nav-item active">
                                <span class="nav-link" style="cursor:pointer" onclick="RC.LoadHome()">Home</span>
                            </li>
                            <li class="nav-item">
                                <!-- <a class="nav-link" href="#" onclick="RC.LoadHome()">Inserir novo carro</a> -->
                            </li>
                        </ul>
                    </div>

            </div>
        </nav>

        <div id="content" class="container">



        </div>
    </body>

</html>
<script src="<?=HOST?>templates/estadao/src/js/main.js"></script>
<style>
    body {
        padding-top: 56px;
    }

</style>
<script>


</script>