<!DOCTYPE html>
<html lang="pt-br">

    <head>
        <meta charset="utf-8">
        <title><?=$this->title?></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                    <a class="navbar-brand" href="#">Estadão</a>
                    <div class="pull-right ">
                        <ul class="navbar-nav ">
                            <li class="nav-item active">
                                <a class="nav-link" href="#" onclick="RC.LoadHome()">Home</a>
                            </li>
                            <li class="nav-item">
                                <!-- <a class="nav-link" href="#" onclick="RC.LoadHome()">Inserir novo carro</a> -->
                            </li>
                        </ul>
                    </div>

            </div>
        </nav>

        <div id="content" class="container">



        </div>
    </body>

</html>
<script src="<?=HOST?>templates/estadao/src/js/main.js"></script>
<style>
    body {
        padding-top: 56px;
    }

</style>
<script>
document.addEventListener("DOMContentLoaded", function(event) { 
    RC.LoadHome();

    document.querySelector("")


});

</script>