version: "3.7"
services:
  web:
    container_name: estadao-test-dev-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
  
  nginx:
    image: nginx:alpine
    container_name: estadao-test-dev-web-nginx
    restart: unless-stopped
    expose:
      - 9003
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - web